---
general:
  server_url: https://my-bitbucket.example.com
  default_title: _Please review the following PRs:_ # <-- You can use Slack message formatting.

projects:
  awesome-project: # <-- Bitbucket root project name.
    repos:         # <-- List of repositories under the project above to check.
      - some-repo
      - other-repo
      - really-cool-repo
      - this-legacy-repo
    channel: C61YU9B0G # <-- Slack channel ID to send the report.

  another-project:
    repos:
      - foo
      - bar
    channel: CXXGXXXXX
